In [5]:
import pandas as pd

df = pd.read_parquet("0000[1].parquet")

df.to_csv("student_placement_raw.csv", index=False)

print("CSV created successfully!")

CSV created successfully!


In [6]:
df.head()


,Internships,CGPA,HistoryOfBacklogs,PlacedOrNot
0,1,8,1,1
1,0,7,1,1
2,1,6,0,1
3,0,8,1,1
4,0,8,0,1


In [7]:
df.shape

(2966, 4)

In [8]:
df.columns

Index(['Internships', 'CGPA', 'HistoryOfBacklogs', 'PlacedOrNot'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2966 entries, 0 to 2965
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Internships        2966 non-null   int64
 1   CGPA               2966 non-null   int64
 2   HistoryOfBacklogs  2966 non-null   int64
 3   PlacedOrNot        2966 non-null   int64
dtypes: int64(4)
memory usage: 92.8 KB


In [10]:
df.isnull().sum()

Internships          0
CGPA                 0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

In [11]:
df.describe()

,Internships,CGPA,HistoryOfBacklogs,PlacedOrNot
count,2966.000000,2966.000000,2966.000000,2966.000000
mean,0.703641,7.073837,0.192178,0.552596
std,0.740197,0.967748,0.394079,0.497310
min,0.000000,5.000000,0.000000,0.000000
25%,0.000000,6.000000,0.000000,0.000000
50%,1.000000,7.000000,0.000000,1.000000
75%,1.000000,8.000000,0.000000,1.000000
max,3.000000,9.000000,1.000000,1.000000


In [12]:
df.duplicated().sum()

np.int64(2911)

In [13]:
df.value_counts().head(10)

Internships  CGPA  HistoryOfBacklogs  PlacedOrNot
0            8     0                  1              328
1            8     0                  1              315
0            7     0                  0              274
1            7     0                  0              233
0            6     0                  0              227
1            6     0                  0              211
             7     0                  1               95
2            8     0                  1               88
             6     0                  1               78
0            6     0                  1               76
Name: count, dtype: int64

In [14]:
df.nunique()

Internships          4
CGPA                 5
HistoryOfBacklogs    2
PlacedOrNot          2
dtype: int64

In [15]:
df["PlacedOrNot"].value_counts()

PlacedOrNot
1    1639
0    1327
Name: count, dtype: int64

In [16]:
df["PlacedOrNot"].value_counts(normalize=True) * 100

PlacedOrNot
1    55.259609
0    44.740391
Name: proportion, dtype: float64

In [18]:
df.dtypes

Internships          int64
CGPA                 int64
HistoryOfBacklogs    int64
PlacedOrNot          int64
dtype: object

In [19]:
df["CGPA"].value_counts().sort_index()

CGPA
5     96
6    834
7    956
8    915
9    165
Name: count, dtype: int64

In [20]:
df["Internships"].value_counts().sort_index()

Internships
0    1331
1    1234
2     350
3      51
Name: count, dtype: int64

In [21]:
(df < 0).sum()

Internships          0
CGPA                 0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

In [22]:
df["CGPA"].between(5, 9).all()

np.True_

In [23]:
df["Internships"].between(0, 3).all()

np.True_

In [24]:
df["HistoryOfBacklogs"].isin([0, 1]).all()

np.True_

In [25]:
df["PlacedOrNot"].isin([0, 1]).all()

np.True_

In [27]:
X = df.drop("PlacedOrNot", axis=1)

In [28]:
y = df["PlacedOrNot"]

In [29]:
X.head()

,Internships,CGPA,HistoryOfBacklogs
0,1,8,1
1,0,7,1
2,1,6,0
3,0,8,1
4,0,8,0


0    1
1    1
2    1
3    1
4    1
Name: PlacedOrNot, dtype: int64

In [31]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (2966, 3)
y shape: (2966,)


In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (2372, 3)
Testing data: (594, 3)


In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling completed!")

Scaling completed!


In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [35]:
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42)
}

print("Models created!")

Models created!


In [36]:
for name, model in models.items():
    model.fit(X_train_scaled, y_train)

print("All models trained successfully!")

All models trained successfully!


In [37]:
predictions = {}

for name, model in models.items():
    predictions[name] = model.predict(X_test_scaled)

print("Predictions completed!")


Predictions completed!


In [38]:
from sklearn.metrics import accuracy_score

for name in models:
    accuracy = accuracy_score(y_test, predictions[name])
    print(name, ":", accuracy)

Logistic Regression : 0.7828282828282829
Decision Tree : 0.8585858585858586
Random Forest : 0.8585858585858586


In [39]:
from sklearn.metrics import classification_report

for name in models:
    print("\n", "="*50)
    print(name)
    print("="*50)
    print(classification_report(y_test, predictions[name]))


Logistic Regression
              precision    recall  f1-score   support

           0       0.77      0.74      0.75       266
           1       0.80      0.82      0.81       328

    accuracy                           0.78       594
   macro avg       0.78      0.78      0.78       594
weighted avg       0.78      0.78      0.78       594


Decision Tree
              precision    recall  f1-score   support

           0       0.78      0.96      0.86       266
           1       0.96      0.78      0.86       328

    accuracy                           0.86       594
   macro avg       0.87      0.87      0.86       594
weighted avg       0.88      0.86      0.86       594


Random Forest
              precision    recall  f1-score   support

           0       0.78      0.96      0.86       266
           1       0.96      0.78      0.86       328

    accuracy                           0.86       594
   macro avg       0.87      0.87      0.86       594
weighted avg       0.88

In [40]:
from sklearn.metrics import confusion_matrix

for name in models:
    print("\n", name)
    print(confusion_matrix(y_test, predictions[name]))


 Logistic Regression
[[197  69]
 [ 60 268]]

 Decision Tree
[[255  11]
 [ 73 255]]

 Random Forest
[[255  11]
 [ 73 255]]


In [41]:
%pip install mlflow

  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.6 MB 6.7 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.6 MB 8.1 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.6 MB 9.3 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 8.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 8.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.6 MB 8.6 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.6 MB 4.8 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.6 MB 4.7 MB/s eta 0:00:01
   ------------------------------


[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [42]:
import mlflow
import mlflow.sklearn

print("MLflow version:", mlflow.__version__)

MLflow version: 3.16.0


In [43]:
mlflow.set_experiment("Student_Placement_Prediction")
print("MLflow experiment created!")

2026/09/11 00:44:33 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/09/11 00:44:33 INFO mlflow.store.db.utils: Updating database tables
2026/09/11 00:44:37 INFO mlflow.tracking.fluent: Experiment with name 'Student_Placement_Prediction' does not exist. Creating a new experiment.


MLflow experiment created!


In [44]:
for name, model in models.items():

    with mlflow.start_run(run_name=name):

        accuracy = accuracy_score(
            y_test,
            model.predict(X_test_scaled)
        )

        mlflow.log_param("model", name)
        mlflow.log_param("test_size", 0.2)
        mlflow.log_param("random_state", 42)

        mlflow.log_metric("accuracy", accuracy)

        mlflow.sklearn.log_model(
            model,
            "model"
        )

        print(name, "logged with accuracy:", accuracy)

2026/09/11 00:44:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


Logistic Regression logged with accuracy: 0.7828282828282829


2026/09/11 00:45:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


Decision Tree logged with accuracy: 0.8585858585858586


2026/09/11 00:45:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


Random Forest logged with accuracy: 0.8585858585858586


In [48]:
results = {}

for name, model in models.items():
    results[name] = accuracy_score(
        y_test,
        model.predict(X_test_scaled)
    )

best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

print("Best Model:", best_model_name)
print("Best Accuracy:", results[best_model_name])

Best Model: Decision Tree
Best Accuracy: 0.8585858585858586


In [47]:
import joblib

joblib.dump(scaler, "scaler.pkl")
joblib.dump(best_model, "best_model.pkl")

print("Model and scaler saved successfully!")

Model and scaler saved successfully!


In [49]:
from mlflow.models import infer_signature

signature = infer_signature(
    X_train_scaled,
    best_model.predict(X_train_scaled)
)

print("Model signature created!")

Model signature created!


In [58]:
with mlflow.start_run(run_name="Best_Model"):

    accuracy = accuracy_score(
        y_test,
        best_model.predict(X_test_scaled)
    )

    mlflow.log_param("best_model", best_model_name)
    mlflow.log_metric("accuracy", accuracy)

    mlflow.sklearn.log_model(
        best_model,
        "model",
        signature=signature
    )

print("Best model logged to MLflow!")

2026/09/11 00:58:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


Best model logged to MLflow!


In [51]:
import mlflow
print("MLflow version:", mlflow.__version__)

MLflow version: 3.16.0


In [52]:
mlflow.set_experiment("Student_Placement_Prediction")

print("MLflow experiment created successfully!")

MLflow experiment created successfully!


In [59]:
import mlflow
import mlflow.sklearn
from sklearn.metrics import accuracy_score

for name, model in models.items():

    with mlflow.start_run(run_name=name):

        model.fit(X_train_scaled, y_train)

        predictions = model.predict(X_test_scaled)

        accuracy = accuracy_score(y_test, predictions)

        mlflow.log_param("model", name)
        mlflow.log_metric("accuracy", accuracy)

        mlflow.sklearn.log_model(model, "model")

        print(name, "Accuracy:", accuracy)

print("All models logged to MLflow successfully!")

2026/09/11 00:58:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/11 00:59:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


Logistic Regression Accuracy: 0.7828282828282829
Decision Tree Accuracy: 0.8585858585858586


2026/09/11 00:59:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.


Random Forest Accuracy: 0.8585858585858586
All models logged to MLflow successfully!


In [60]:
from sklearn.metrics import precision_score

for name in models:
    print(name, "Precision:", precision_score(y_test, models[name].predict(X_test_scaled)))

Logistic Regression Precision: 0.7952522255192879
Decision Tree Precision: 0.9586466165413534
Random Forest Precision: 0.9586466165413534


In [61]:
from sklearn.metrics import recall_score

for name in models:
    print(name, "Recall:", recall_score(y_test, models[name].predict(X_test_scaled)))

Logistic Regression Recall: 0.8170731707317073
Decision Tree Recall: 0.7774390243902439
Random Forest Recall: 0.7774390243902439


In [62]:
from sklearn.metrics import f1_score

for name in models:
    print(name, "F1 Score:", f1_score(y_test, models[name].predict(X_test_scaled)))

Logistic Regression F1 Score: 0.806015037593985
Decision Tree F1 Score: 0.8585858585858586
Random Forest F1 Score: 0.8585858585858586


In [63]:
from sklearn.metrics import confusion_matrix

for name in models:
    print("\n", name)
    print(confusion_matrix(y_test, models[name].predict(X_test_scaled)))


 Logistic Regression
[[197  69]
 [ 60 268]]

 Decision Tree
[[255  11]
 [ 73 255]]

 Random Forest
[[255  11]
 [ 73 255]]


In [64]:
results = {}

for name in models:
    pred = models[name].predict(X_test_scaled)
    results[name] = accuracy_score(y_test, pred)

print(results)

{'Logistic Regression': 0.7828282828282829, 'Decision Tree': 0.8585858585858586, 'Random Forest': 0.8585858585858586}


In [65]:
best_model_name = "Random Forest"
best_model = models[best_model_name]

print("Best Model:", best_model_name)

Best Model: Random Forest


In [66]:
import joblib

joblib.dump(best_model, "best_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model and scaler saved successfully!")

Model and scaler saved successfully!


In [67]:
from mlflow.models import infer_signature

signature = infer_signature(
    X_train_scaled,
    best_model.predict(X_train_scaled)
)

print("Model signature created!")

Model signature created!


In [68]:
best_accuracy = accuracy_score(
    y_test,
    best_model.predict(X_test_scaled)
)

print("Best Model:", best_model_name)
print("Best Accuracy:", best_accuracy)

Best Model: Random Forest
Best Accuracy: 0.8585858585858586


In [69]:
print("Files saved:")
import os

print(os.listdir())

Files saved:
['-1.14-windows.xml', '.android', '.aws', '.bash_history', '.cache', '.config', '.dotnet', '.dvc', '.dvcignore', '.eclipse', '.git', '.gitconfig', '.gradle', '.ipynb_checkpoints', '.ipython', '.jdks', '.jupyter', '.keras', '.lemminx', '.lesshst', '.m2', '.matplotlib', '.ms-ad', '.node_repl_history', '.openjfx', '.p2', '.packettracer', '.redhat', '.ssh', '.streamlit', '.templateengine', '.vscode', '.vscode-shared', '0000[1].parquet', 'AndroidStudioProjects', 'AppData', 'Application Data', 'best_model.pkl', 'bgame', 'bgbg', 'bgg', 'bikeegame', 'bikegame', 'bikgame', 'bookingTravel', 'chat-app-backend', 'chat-app-dashboard', 'Cisco Packet Tracer 9.0.0', 'clgProjects', 'Contacts', 'Cookies', 'cpp', 'CrossDevice', 'cscript', 'DaVinci Resolve Media', 'Desktop', 'Documents', 'download.png', 'Downloads', 'Dropbox', 'E-Comm', 'eclipse-workspace', 'Favorites', 'fire base Auth Test', 'formm', 'formvalidation', 'gamee', 'ibisPaint', 'IdeaProjects', 'image editor', 'java', 'js', 'leetc

In [71]:
with mlflow.start_run(run_name="Random_Forest_Production") as run:
    run_id = run.info.run_id

    accuracy = accuracy_score(
        y_test,
        best_model.predict(X_test_scaled)
    )

    mlflow.log_param("model", "Random Forest")
    mlflow.log_metric("accuracy", accuracy)

    mlflow.sklearn.log_model(
        best_model,
        name="random_forest_model",
        signature=signature
    )

print("Run ID:", run_id)

Run ID: eed8385587064e28ab42ae8bf225334e


In [72]:
registered_model_name = "StudentPlacementPredictionModel"

print(registered_model_name)

StudentPlacementPredictionModel


In [73]:
model_uri = f"runs:/{run_id}/random_forest_model"

registered_model = mlflow.register_model(
    model_uri=model_uri,
    name=registered_model_name
)

print("Model registered successfully!")

Successfully registered model 'StudentPlacementPredictionModel'.
2026/09/11 01:03:15 WARNING mlflow.tracking._model_registry.fluent: Run with id eed8385587064e28ab42ae8bf225334e has no artifacts at artifact path 'random_forest_model', registering model based on models:/m-0422ba3d05074511ae65f2e790d1ff4f instead
Created version '1' of model 'StudentPlacementPredictionModel'.


Model registered successfully!


In [74]:
print("Model Name:", registered_model.name)
print("Model Version:", registered_model.version)

Model Name: StudentPlacementPredictionModel
Model Version: 1


In [75]:
print("MLflow Tracking URI:")
print(mlflow.get_tracking_uri())

MLflow Tracking URI:
sqlite:///C:/Users/chinn/mlflow.db


In [76]:
import mlflow
print(mlflow.get_tracking_uri())

sqlite:///C:/Users/chinn/mlflow.db
